### ISSUE TITLE
Migrate to an http library which doesn't depend on tokio

### ISSUE THREAD

**Issue by nuxeh** [nuxeh/aocf#17]
Tokio (via reqwest) results in a fairly large dependency tree for simple use of the crate, which isn't ideal.

**Comment by tocklime** [comment]
I just use the crate to download the inputs in my solution executables. I don't need any of the html2md stuff. Would be nice if I could disable the bits I don't need with feature flags, or any other way to reduce the compilation weight of this crate, would be great.

**Comment by nuxeh** [comment]
Indeed, I think this phenomenon is most apparent when you just use the struct from the crate, and still have to build `tokio`, it's not ideal...

But the HTTP lib is a firm requirement for the functioning of the crate standalone, too, so to reduce it would mean replacing the HTTP lib, I think.

Features is a good idea, but as far as I recall there aren't too many heavy ones besides `reqwest` and its dependencies, so no candidates for feature gating spring to mind just now, unless you spotted something specific which could be trimmed out?

**Comment by nuxeh** [comment]
Looking at the code, `sqlite` is part of the basic crate, didn't expect that to be the case, have a feeling this is more a CLI specific function really. So that could certainly be disabled in features, @tocklime 

I might look at moving that code into the CLI, too.

**Comment by nuxeh** [comment]
@tocklime I just did this, it appears to work, although I will wait until tomorrow to check that submission still works fully, after that i'll make a new release. If you wish to try out the branch until then, feel free!

**Comment by tocklime** [comment]
Thanks, that seems to work, and has made my `cargo tree` a bit smaller :)
