### ISSUE TITLE
Proposal: switch to user-based setup

### ISSUE THREAD

**Issue by tranzystorekk** [nuxeh/aocf#44]
Disclaimer: this is based on my  personal `aocf` workflow, discussion welcome!

I'd like to propose that `aocf` switches to a more global, per-user mode of operation.
It would mean that there is no longer a repository created in the CWD, e.g. `./.aocf/`, but rather that specific parts of aocf are kept in XDG-based dirs, e.g.:

- cookie file in `$XDG_STATE_HOME/aocf`, aka `$HOME/.local/state/aocf`
- config file in `$XDG_DATA_HOME/aocf`, aka `$HOME/.local/share/aocf` (potentially split the checkout data into a file in the cookie directory above)
- cache files in `$XDG_CACHE_HOME/aocf` aka `$HOME/.cache/aocf`

This makes the whole tool more predictable, and makes it work uniformly no matter where `aocf` is called from.

**Comment by tranzystorek-io** [comment]
I'm already partway into a rough implementation of this idea that uses `dirs` everywhere for those XDG specs, but there's some refactoring and cleanup to be done before I can submit a PR.

**Comment by tranzystorek-io** [comment]
Note, instead of merging this in here I went ahead and created a tool inspired by `aocf` but with the above changes as well as some more adjustments: https://github.com/tranzystorek-io/arrive
